# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1611887980);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1611918555);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1611930371);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1611887860);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1611918795);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1611887740);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1611918915);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1611918675);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1611887590);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 59);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8dd21bd4-160f-4f67-8862-4f120b746427}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1611849600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1611918534);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1611930345193");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1611932135193");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1611918537117");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611940137117");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180208175058");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1611930343");
user_pref("browser.slowStartup.averageTime", 5467);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180208175058");
user_pref("browser.startup.homepage_override.mstone", "58.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":13,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1611887595342");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "58.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180208175058");
user_pref("extensions.lastAppVersion", "58.0.2");
user_pref("extensions.lastPlatformVersion", "58.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "1f869aa0-d7bb-432d-a878-d5f92ea67b0e");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8744d35d-39b1-4f9d-8b5f-60eeb61ed700}\",\"addons\":{\"hotfix-bug-1548973@mozilla.org\":{\"version\":\"1.1.4\"}}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"790ee12c-5265-4628-9950-9e29eee044af\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1611887615);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180208175058");
user_pref("media.gmp-manager.lastCheck", 1611887613);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1611918379);
user_pref("services.blocklist.clock_skew_seconds", 177);
user_pref("services.blocklist.gfx.checked", 1611918379);
user_pref("services.blocklist.last_etag", "\"1611907095284\"");
user_pref("services.blocklist.last_update_seconds", 1611918379);
user_pref("services.blocklist.onecrl.checked", 1611918379);
user_pref("services.blocklist.pinning.checked", 1611918379);
user_pref("services.blocklist.plugins.checked", 1611918379);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1611930341);
user_pref("toolkit.telemetry.cachedClientID", "5d787ccb-0493-48b8-85eb-06a23aed8d8f");
user_pref("toolkit.telemetry.previousBuildID", "20180208175058");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
